import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MenuBar from "./_component/Menubar";
import ReduxProvider from "@/lib/store";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Redux Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
        <header className="bg-blue-900  text-center p-4">
        <h1  className="text-5xl text-white" >
           TODO Redux</h1>
         
        <div className="p-4 text-xl  text-white space-x-3">
                  <hr/>
           <MenuBar/>
        <hr/>
        </div>
        </header>

         <div className="m-5">
        {children}
        </div>

         <footer className="bg-blue-900 text-White text-center bottom-0 w-full fixed text-xl">
          &copy; developed by Rahul Yadav
         </footer>
        </ReduxProvider>
      </body>
    </html>
  );
}
